# Generated by Django 4.1.4 on 2022-12-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akifpenstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
